In [2]:
import pandas as pd

# CREAMOS UN DATAFRAME DE PRUEBA

In [3]:
df = pd.DataFrame(
    data= {
        "a":list('asdfasdfas'),
        "b":range(0,10)
    }
)
df

   a  b
0  a  0
1  s  1
2  d  2
3  f  3
4  a  4
5  s  5
6  d  6
7  f  7
8  a  8
9  s  9

# GENERAMOS VALORES NULOS

In [4]:
df.iloc[2:5,0] = None
df.iloc[6:7,1] = None
df

      a    b
0     a  0.0
1     s  1.0
2  None  2.0
3  None  3.0
4  None  4.0
5     s  5.0
6     d  NaN
7     f  7.0
8     a  8.0
9     s  9.0

# VERIFICAMOS VALORES NULO

In [5]:
df.isna()

       a      b
0  False  False
1  False  False
2   True  False
3   True  False
4   True  False
5  False  False
6  False   True
7  False  False
8  False  False
9  False  False

# CONTEO DE NULOS

In [6]:
df.isna().sum()

a    3
b    1
dtype: int64

# CONTEO TOTAL DE NULOS

In [7]:
df.isna().sum().sum()

4

# CONTEO POR CASOS

In [8]:
df.isna().pipe(
    lambda df_1: (
        df_1.sum()
        .reset_index(name='n_missing')
        .rename(columns={'index':'variable'})
        .assign(
            n_cases=len(df_1),
            pct_missing=lambda df_2: df_2.n_missing / df_2.n_cases * 100,
        )
    )
)

  variable  n_missing  n_cases  pct_missing
0        a          3       10         30.0
1        b          1       10         10.0